### ISSUE TITLE
Local Directories are not supported as Modules

### ISSUE THREAD

**Issue by DougMidgley** [salesforce/lwc-webpack-plugin#10]
When loading lightning-base-components the entire config is working lovely, and I would like to work on my own modules which can be loaded to NPM.
The challenge is that I don't want to push them to NPM until they are working as expecting (this is in collaboration with another app).
The issue I am seeing is that when do 
`npm  i my/local/path`

it does not seem to support, and I get the following error from webpack when building from the main app and trying to pull in the components from the module bundle (sfmc-custom-sdk)

`ERROR in ../sfmc-custom-sdk/src/modules/common/notfound/notfound.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>.....`

If I move the folder into node_modules then it does work again, but it means it is at risk of being overwritten easily, so I want to avoid this. 

Is there any thought put into these scenarios or is this just going to be one of those limitations?

**Comment by nolanlawson** [comment]
Hi @DougMidgley thanks for the bug report. I'm a bit unsure how to reproduce it, though. By any chance do you have a minimal repro where I can understand how to reproduce the bug? Otherwise I'm not sure if it's a bug in `lwc-webpack-plugin`, `lightning-base-components`, or the `sfmc-custom-sdk` you mention. Thanks!

**Comment by DougMidgley** [comment]
Hey @nolanlawson  - i was just prepping an example to push here but seems i cannot replicate, lemme go back to build and if it is resolved then will close in coming week :)

**Comment by DougMidgley** [comment]
Difference was due to Yarn copying (npm does copy, it links). Unsure if underlying issue of npm causes issues for others, but workaround is use Yarn for now ;)
