### ISSUE TITLE
DOCUMENTATION : inefficient link provided in README

### ISSUE THREAD

**Issue by RupertBarrow** [salesforce/lwc-webpack-plugin#23]
The options `stylesheetConfig`and `outputConfig`are not documpented in the link provided in the "Usage" paragraph of the README.md file

**Comment by nolanlawson** [comment]
Good catch. `stylesheetConfig` is documented [here](https://github.com/salesforce/lwc/blob/56a191a7a4a9280970c5ada3cd964f2c4c013bb2/packages/%40lwc/rollup-plugin/README.md#options) and `outputConfig` seems undocumented, but looks like it's defined [here](https://github.com/salesforce/lwc/blob/56a191a7a4a9280970c5ada3cd964f2c4c013bb2/packages/%40lwc/compiler/src/transformers/javascript.ts#L26). We should probably have a canonical place to point to this documentation.
